export const resData = [
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "805434",
          name: "Mehfil",
          city: "3",
          slugs: {
            restaurant: "mehfil-ameerpet-ameerpet",
            city: "hyderabad",
          },
          cloudinaryImageId: "287bbac3f2e6e490b18c24082c096183",
          address:
            "7-1-282/C/1/4, Ground Floor, First Floor & Second Floor, BK Guda, Balkampet Main Road, Hyderabad, Hyderabad, Telangana-500038",
          locality: "Mahatma Gandhi Nagar",
          areaName: "Ameerpet",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Biryani", "Chinese", "Kebabs", "Tandoor"],
          avgRating: 4.1,
          feeDetails: {},
          avgRatingString: "4.1",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 67,
            minDeliveryTime: 65,
            maxDeliveryTime: 70,
            lastMileTravel: 5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "65-70 MINS",
            lastMileTravelString: "5.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {
            imageBadges: [
              {
                imageId: "Rxawards/_CATEGORY-Biryani.png",
                description: "Delivery!",
              },
              {
                imageId: "Rxawards/_CATEGORY-Shawarma.png",
                description: "Delivery!",
              },
            ],
          },
          aggregatedDiscountInfoV3: {
            header: "30% OFF",
            subHeader: "UPTO ₹75",
          },
          ratingSlab: "RATING_SLAB_5",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "805434",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "805434",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "324746",
          name: "Lucky Restaurant",
          city: "3",
          slugs: {
            restaurant: "lucky-restaurant-kukatpally-kukatpally",
            city: "hyderabad",
          },
          cloudinaryImageId: "r7rdvstukvlj7m06drfx",
          address:
            " 36-168  Devamma basti jagathgirigutta kukatpally hyderabad 500037",
          locality: "Jagathgirigutta",
          areaName: "Devamma Basti",
          costForTwo: "40000",
          costForTwoMessage: "₹400 FOR TWO",
          cuisines: ["Indian"],
          avgRating: 2.6,
          feeDetails: {},
          avgRatingString: "2.6",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 41,
            minDeliveryTime: 40,
            maxDeliveryTime: 45,
            lastMileTravel: 4.3,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "40-45 MINS",
            lastMileTravelString: "4.3 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          aggregatedDiscountInfo: {
            visible: true,
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV2: {
            visible: true,
          },
          ratingSlab: "RATING_SLAB_3",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "324746",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            restaurant_id: "324746",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "21947",
          name: "My Friends Circle Restaurant",
          city: "3",
          slugs: {
            restaurant:
              "my-friends-circle-restaurant-medchal-road-sainikpuri-test",
            city: "hyderabad",
          },
          cloudinaryImageId: "9862ca30a502607090b089bb675cf9e3",
          address:
            "Plot No. 8, Near Laxmi Plaza, Near Suchitra Circle, Medchal Road, Ramraju Nagar, Ramraj Nagar, Ramraju Nagar, Jeedimetla, Secunderabad",
          locality: "Medchal",
          areaName: "Medchal",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Biryani", "Chinese", "Kebabs", "Tandoor"],
          avgRating: 4.1,
          feeDetails: {},
          avgRatingString: "4.1",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 66,
            minDeliveryTime: 65,
            maxDeliveryTime: 70,
            lastMileTravel: 6,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "65-70 MINS",
            lastMileTravelString: "6.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "₹50 OFF",
            subHeader: "ABOVE ₹499",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_5",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "4.0",
              ratingCount: "10K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "21947",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "21947",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "684252",
          name: "Red Bucket Biryani",
          city: "3",
          slugs: {
            restaurant: "red-bucket-biryani-suchitra-circle-suchitra-circle",
            city: "hyderabad",
          },
          cloudinaryImageId:
            "FOOD_CATALOG/IMAGES/CMS/2024/4/24/212402d5-8fe2-4a05-ba46-3d40fa285084_afbf13db-770c-42d6-8941-057b39864e67.jpeg",
          address:
            "HNO:07-001/236/01/NR,PLOTN0:548,GOUND FLOOR & FIRST FLOOR,SUBHASH NAGAR,SUCHITRA ,HYDERABAD",
          locality: "Subhash nagar",
          areaName: "Suchitra Circle",
          costForTwo: "60000",
          costForTwoMessage: "₹600 FOR TWO",
          cuisines: ["Biryani", "Seafood"],
          avgRating: 4,
          feeDetails: {},
          avgRatingString: "4.0",
          totalRatingsString: "500+",
          sla: {
            deliveryTime: 35,
            minDeliveryTime: 35,
            maxDeliveryTime: 40,
            lastMileTravel: 4.4,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "35-40 MINS",
            lastMileTravelString: "4.4 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          aggregatedDiscountInfoV3: {
            header: "₹75 OFF",
            subHeader: "ABOVE ₹199",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "684252",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            restaurant_id: "684252",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "271766",
          name: "Chickpet Donne Biryani,S.R Nagar",
          city: "3",
          slugs: {
            restaurant: "chickpet-donne-biryani-house-ameerpet-ameerpet",
            city: "hyderabad",
          },
          cloudinaryImageId: "p1xgopxnlbn6mdvk1d9h",
          address:
            "25/3RT, SANJEEVA REDDY NAGAR, AMEERPET, Khairatabad Circle No.17 , Hyderabad, Telangana-500038",
          locality: "Ameerpet",
          areaName: "Sanjeeva Reddy Nagar",
          costForTwo: "40000",
          costForTwoMessage: "₹400 FOR TWO",
          cuisines: ["Indian"],
          avgRating: 4.2,
          feeDetails: {},
          avgRatingString: "4.2",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 50,
            minDeliveryTime: 50,
            maxDeliveryTime: 55,
            lastMileTravel: 6.5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "50-55 MINS",
            lastMileTravelString: "6.5 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {
            textExtendedBadges: [
              {
                iconId: "guiltfree/GF_Logo_android_3x",
                shortDescription: "options available",
                fontColor: "#7E808C",
              },
            ],
          },
          aggregatedDiscountInfoV3: {
            header: "₹100 OFF",
            subHeader: "ABOVE ₹299",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_5",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "271766",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "271766",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "80805",
          name: "Victoria Restaurant",
          city: "3",
          slugs: {
            restaurant:
              "victoria-restaurant-motinagar-moosapet-motinagar-moosapet",
            city: "hyderabad",
          },
          cloudinaryImageId: "a390arrvxwcpzmrhozw3",
          address: "Bhavani Nagar, Moosapet, Hyderabad, Telangana 500018",
          locality: "Moosapet",
          areaName: "Moosapet",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Biryani", "Indian", "Chinese", "Tandoor"],
          avgRating: 3.8,
          feeDetails: {},
          avgRatingString: "3.8",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 30,
            minDeliveryTime: 25,
            maxDeliveryTime: 30,
            lastMileTravel: 5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "25-30 MINS",
            lastMileTravelString: "5.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "10% OFF",
            subHeader: "ABOVE ₹1300",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.0",
              ratingCount: "2",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "80805",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "80805",
            query: "Chicken Biryani",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "349964",
          name: "Biryani House",
          city: "3",
          slugs: {
            restaurant:
              "biryani-house-jeedimetla-&-chintal-jeedimetla-&-chintal",
            city: "hyderabad",
          },
          cloudinaryImageId: "ef4rzlhnjpimyd3o1wqb",
          address:
            "Biryani House, Suchitra Road, beside Godavari Homes, Suchitra, Godavari Homes, Jeedimetla, Hyderabad, Telangana, India",
          locality: "Jeedimetla & Chintal",
          areaName: "Quthbullapur",
          costForTwo: "20000",
          costForTwoMessage: "₹200 FOR TWO",
          cuisines: ["Biryani", "Chinese", "Kebabs", "shawarma", "Beverages"],
          avgRating: 3.8,
          feeDetails: {},
          avgRatingString: "3.8",
          totalRatingsString: "5K+",
          sla: {
            deliveryTime: 36,
            minDeliveryTime: 35,
            maxDeliveryTime: 40,
            lastMileTravel: 4.9,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "35-40 MINS",
            lastMileTravelString: "4.9 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          aggregatedDiscountInfoV3: {
            header: "20% OFF",
            subHeader: "ABOVE ₹700",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "349964",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "349964",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "172111",
          name: "Shadab Go",
          city: "3",
          slugs: {
            restaurant: "shadab-food-court-city-as-rao-nagar-sainikpuri",
            city: "hyderabad",
          },
          cloudinaryImageId: "a6938a7bffb46dfe5786a4054da87162",
          address:
            "26-A, Sanjeeva Reddy Nagar Rd, Vengal Rao Nagar, Sanjeeva Reddy Nagar, Hyderabad, Telangana 500038",
          locality: "SR Nagar",
          areaName: "S R Nagar",
          costForTwo: "50000",
          costForTwoMessage: "₹500 FOR TWO",
          cuisines: ["Biryani", "Chinese", "Haleem"],
          avgRating: 4.2,
          feeDetails: {},
          avgRatingString: "4.2",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 54,
            minDeliveryTime: 50,
            maxDeliveryTime: 55,
            lastMileTravel: 7,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "50-55 MINS",
            lastMileTravelString: "7.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          aggregatedDiscountInfoV3: {
            header: "₹150 OFF",
            subHeader: "ABOVE ₹499",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_5",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "4.0",
              ratingCount: "1K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "172111",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "172111",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "398865",
          name: "Satti babu Biryani",
          city: "3",
          slugs: {
            restaurant: "satti-babu-biryani-kukatpally-kukatpally",
            city: "hyderabad",
          },
          cloudinaryImageId: "vkq8pjxfoe137p4m6bqi",
          address:
            "#11-5-151/1, Pillar no 895, bhavani nagar,Moosapet, Hyderabad,500018",
          locality: "Kukatpally",
          areaName: "Moosapet",
          costForTwo: "40000",
          costForTwoMessage: "₹400 FOR TWO",
          cuisines: [
            "Biryani",
            "Andhra",
            "Beverages",
            "Hyderabadi",
            "Fast Food",
            "Snacks",
            "Indian",
          ],
          avgRating: 3.9,
          feeDetails: {},
          avgRatingString: "3.9",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 38,
            minDeliveryTime: 35,
            maxDeliveryTime: 40,
            lastMileTravel: 5.5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "35-40 MINS",
            lastMileTravelString: "5.5 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          aggregatedDiscountInfo: {
            visible: true,
          },
          badges: {},
          aggregatedDiscountInfoV2: {
            visible: true,
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "398865",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            source: "SEARCH",
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "398865",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "120129",
          name: "Shah Ghouse Hotel & Restaurant",
          city: "3",
          slugs: {
            restaurant: "shah-ghouse-hotel-restaurant-kondapur-kondapur",
            city: "hyderabad",
          },
          cloudinaryImageId: "bzzboei5q647sr0zgz2g",
          address:
            "2-25/A, Beside Apollo Hospital, Near Kondapur Kothaguda 'X' Road, Kondapur, Hyderabad",
          locality: "Kothaguda",
          areaName: "Land Mark Residency",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Biryani", "Chinese", "Mughlai", "Tandoor"],
          avgRating: 4.1,
          feeDetails: {},
          avgRatingString: "4.1",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 75,
            minDeliveryTime: 70,
            maxDeliveryTime: 75,
            lastMileTravel: 13.9,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "70-75 MINS",
            lastMileTravelString: "13.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          aggregatedDiscountInfo: {
            visible: true,
          },
          badges: {
            imageBadges: [
              {
                imageId: "Rxawards/_CATEGORY-Biryani.png",
                description: "Delivery!",
              },
              {
                imageId: "Rxawards/_CATEGORY-Mughlai.png",
                description: "Delivery!",
              },
            ],
          },
          sld: true,
          aggregatedDiscountInfoV2: {
            visible: true,
          },
          ratingSlab: "RATING_SLAB_5",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.4",
              ratingCount: "5K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "120129",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            restaurant_id: "120129",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "802968",
          name: "Bakki Biryani House",
          city: "3",
          slugs: {
            restaurant:
              "bakki-biryani-house-jeedimetla-&-chintal-jeedimetla-&-chintal",
            city: "hyderabad",
          },
          cloudinaryImageId: "d390a6c080d7fa9a3a89f48100ca20b1",
          address:
            "H.No.48-465, Ganesh Bhavan, Ganesh Nagar, Main Road, Chinthal, Quthbullapur Mandal, Medchal, Medchal-Malkajgiri, Telangana-500054",
          locality: "Ganesh Nagar",
          areaName: "Jeedimetla & Chintal",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Biryani", "Arabian"],
          avgRating: 3.7,
          feeDetails: {},
          avgRatingString: "3.7",
          totalRatingsString: "10+",
          sla: {
            deliveryTime: 43,
            minDeliveryTime: 40,
            maxDeliveryTime: 45,
            lastMileTravel: 1.5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "40-45 MINS",
            lastMileTravelString: "1.5 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          aggregatedDiscountInfoV3: {
            header: "₹75 OFF",
            subHeader: "ABOVE ₹299",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "802968",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            source: "SEARCH",
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "802968",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "619437",
          name: "New Sagar Restaurant & Bakers",
          city: "3",
          slugs: {
            restaurant:
              "new-sagar-restaurant-&-bakers-jeedimetla-&-chintal-jeedimetla-&-chintal",
            city: "hyderabad",
          },
          cloudinaryImageId:
            "FOOD_CATALOG/IMAGES/CMS/2024/5/8/092e4cb9-7274-43d4-9bbe-d04e7445153d_e1555254-32f0-4b39-9d41-dfb30f49e7df.jpg",
          address:
            "02-020/NR, SURARAM, GAJULARAMARA, GAJULARAMARAM CIRCLE NO 26, HYDERABAD, TELANGANA-500055",
          locality: "Jeedimetla",
          areaName: "Suraram",
          costForTwo: "40000",
          costForTwoMessage: "₹400 FOR TWO",
          cuisines: ["Indian", "Chinese", "Fast Food"],
          avgRating: 4.1,
          feeDetails: {},
          avgRatingString: "4.1",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 63,
            minDeliveryTime: 60,
            maxDeliveryTime: 65,
            lastMileTravel: 7.5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "60-65 MINS",
            lastMileTravelString: "7.5 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "40% OFF",
            subHeader: "UPTO ₹80",
          },
          ratingSlab: "RATING_SLAB_5",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.9",
              ratingCount: "5K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "619437",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "619437",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "691909",
          name: "Kritunga",
          city: "3",
          slugs: {
            restaurant: "kritunga-restaurant-kukatpally-kukatpally-2",
            city: "hyderabad",
          },
          cloudinaryImageId: "rdhyw0tkwjy9fu1gi0td",
          address:
            "11-5-266/2,BHARATHNAGAR MAIN ROAD MOOSAPET HYDERABAD , 500018",
          locality: "Bharathnagar",
          areaName: "Kukatpally",
          costForTwo: "50000",
          costForTwoMessage: "₹500 FOR TWO",
          cuisines: [
            "Chinese",
            "Salads",
            "North Indian",
            "Tandoor",
            "Biryani",
            "Beverages",
            "Desserts",
          ],
          avgRating: 3.8,
          feeDetails: {},
          avgRatingString: "3.8",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 42,
            minDeliveryTime: 40,
            maxDeliveryTime: 45,
            lastMileTravel: 5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "40-45 MINS",
            lastMileTravelString: "5.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          aggregatedDiscountInfoV3: {
            header: "20% OFF",
            subHeader: "ABOVE ₹700",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "691909",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "691909",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "698454",
          name: "Chickpet Donne Biryani House",
          city: "3",
          slugs: {
            restaurant: "chickpet-donne-biryani-house-ameerpet-ameerpet-2",
            city: "hyderabad",
          },
          cloudinaryImageId: "8fa4d0add60eb8bf32a5ae1742ca3a9a",
          address:
            "Door no 7-1-405 1st floor balkampet road, ammerpet,hyderabad, telangana 500016",
          locality: "Balkampet Road",
          areaName: "Ameerpet",
          costForTwo: "20000",
          costForTwoMessage: "₹200 FOR TWO",
          cuisines: ["Biryani", "Fast Food", "Snacks"],
          avgRating: 4.2,
          feeDetails: {},
          avgRatingString: "4.2",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 63,
            minDeliveryTime: 60,
            maxDeliveryTime: 65,
            lastMileTravel: 6.2,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "60-65 MINS",
            lastMileTravelString: "6.1 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          aggregatedDiscountInfoV3: {
            header: "₹150 OFF",
            subHeader: "ABOVE ₹999",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_5",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "698454",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "698454",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "436805",
          name: "Lucky Multicuisine Restaurant",
          city: "3",
          slugs: {
            restaurant: "lucky-multicuisine-restaurant-madhapur-madhapur",
            city: "hyderabad",
          },
          cloudinaryImageId: "cfe2e23beb3257a7cf75ca3a0ed36e01",
          address:
            "Metro Pillar Number C1722, Hitech City Rd, Kavuri Hills, Madhapur, Hyderabad, Telangana 500033",
          locality: "Guttalabegumpet",
          areaName: "Madhapur",
          costForTwo: "40000",
          costForTwoMessage: "₹400 FOR TWO",
          cuisines: ["Haleem", "Biryani", "North Indian", "Chinese"],
          avgRating: 3.7,
          feeDetails: {},
          avgRatingString: "3.7",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 75,
            minDeliveryTime: 75,
            maxDeliveryTime: 80,
            lastMileTravel: 12.8,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "75-80 MINS",
            lastMileTravelString: "12.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "15% OFF",
            subHeader: "ABOVE ₹1000",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.8",
              ratingCount: "5K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "436805",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "436805",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "4123",
          name: "Hotel Sitara Grand - Dhanturi Group of hotels",
          city: "3",
          slugs: {
            restaurant: "hotel-sitara-grand-kukatpally",
            city: "hyderabad",
          },
          cloudinaryImageId: "fup8lrzrx0anyztp0frk",
          address:
            "1st Road, 1st Phase, MIG 21, 22, KPHB Colony, Kukatpally, Hyderabad",
          locality: "KPHB Phase 1",
          areaName: "Kukatpally",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Biryani", "Chinese", "South Indian", "Tandoor"],
          avgRating: 4,
          feeDetails: {},
          avgRatingString: "4.0",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 67,
            minDeliveryTime: 65,
            maxDeliveryTime: 70,
            lastMileTravel: 7.5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "65-70 MINS",
            lastMileTravelString: "7.5 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          aggregatedDiscountInfo: {
            visible: true,
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV2: {
            visible: true,
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "4123",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "4123",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "439120",
          name: "Hotel Swagath Grand - Dhanturi Group of Hotels",
          city: "3",
          slugs: {
            restaurant: "fishland-express-kukatpally-kukatpally",
            city: "hyderabad",
          },
          cloudinaryImageId: "fup8lrzrx0anyztp0frk",
          address:
            "No. 1-228, KPHB main road, beside bata, kukatpally, hyd - 500072",
          locality: "Kukatpally",
          areaName: "Kukatpally",
          costForTwo: "50000",
          costForTwoMessage: "₹500 FOR TWO",
          cuisines: [
            "Biryani",
            "Tandoor",
            "Chinese",
            "Seafood",
            "Beverages",
            "Desserts",
          ],
          avgRating: 3.9,
          feeDetails: {},
          avgRatingString: "3.9",
          totalRatingsString: "5K+",
          sla: {
            deliveryTime: 59,
            minDeliveryTime: 55,
            maxDeliveryTime: 60,
            lastMileTravel: 7.3,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "55-60 MINS",
            lastMileTravelString: "7.3 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "20% OFF",
            subHeader: "ABOVE ₹600",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.6",
              ratingCount: "1K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "439120",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            restaurant_id: "439120",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "87606",
          name: "Ratna Bawarchi",
          city: "3",
          slugs: {
            restaurant: "ratna-bawarchi-kukatpally-kukatpally",
            city: "hyderabad",
          },
          cloudinaryImageId:
            "FOOD_CATALOG/IMAGES/CMS/2024/6/5/7ac4b107-c168-45f0-a168-32f674f359c9_266ff675-2b8e-4180-b254-18298d002730.jpg",
          address:
            "Vijaya Nagar Colony, Kukatpally, Hyderabad, Telangana 500072",
          locality: "Kukatpally",
          areaName: "Kukatpally",
          costForTwo: "40000",
          costForTwoMessage: "₹400 FOR TWO",
          cuisines: ["Biryani", "Hyderabadi"],
          avgRating: 3.5,
          feeDetails: {},
          avgRatingString: "3.5",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 55,
            minDeliveryTime: 50,
            maxDeliveryTime: 55,
            lastMileTravel: 5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "50-55 MINS",
            lastMileTravelString: "5.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          aggregatedDiscountInfo: {
            visible: true,
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV2: {
            visible: true,
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.3",
              ratingCount: "50+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "87606",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            restaurant_id: "87606",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "809512",
          name: "Mehfel Restaurant",
          city: "3",
          slugs: {
            restaurant: "mehfel-restaurant-kukatpally-kukatpally",
            city: "hyderabad",
          },
          cloudinaryImageId: "a92bb49c8ada7726bca14d7e84acdd43",
          address:
            "HOUSE NO.5-4-58/9 ,MYTHRI  NAGAR ,KUKATPALLY, Kukatpally Circle No  24, Hyderabad, Telangana - 500072",
          locality: "Mythri Nagar",
          areaName: "Kukatpally",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Indian", "Biryani", "Chinese"],
          avgRating: 2.8,
          feeDetails: {},
          avgRatingString: "2.8",
          totalRatingsString: "100+",
          sla: {
            deliveryTime: 73,
            minDeliveryTime: 70,
            maxDeliveryTime: 75,
            lastMileTravel: 3.7,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "70-75 MINS",
            lastMileTravelString: "3.7 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "₹75 OFF",
            subHeader: "ABOVE ₹299",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_3",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "809512",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "809512",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "248771",
          name: "Raju Gari Biryani",
          city: "3",
          slugs: {
            restaurant: "raju-gari-biryani-gachibowli-gachibowli",
            city: "hyderabad",
          },
          cloudinaryImageId: "vbrfl0xqmfuvqua42ix8",
          address: "PLOT NO-64, AYYAPA SOCIETY,MADHAPUR,HYDERABAD,INDIA,500081",
          locality: "AYYAPA SOCIETY, MADHAPUR.",
          areaName: "Madhapur",
          costForTwo: "20000",
          costForTwoMessage: "₹200 FOR TWO",
          cuisines: ["Biryani", "Snacks", "Chinese", "Mughlai"],
          avgRating: 3.7,
          feeDetails: {},
          avgRatingString: "3.7",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 59,
            minDeliveryTime: 55,
            maxDeliveryTime: 60,
            lastMileTravel: 10.9,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "55-60 MINS",
            lastMileTravelString: "10.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "₹150 OFF",
            subHeader: "ABOVE ₹299",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "248771",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "248771",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "89762",
          name: "Prince Bawarchi",
          city: "3",
          slugs: {
            restaurant: "prince-bawarchi-hitech-city-madhapur",
            city: "hyderabad",
          },
          cloudinaryImageId: "mkfo2pimx5oouxqtx7a8",
          address: "Siddhi Vinayak Nagar, Hitech City, Hyderabad",
          locality: "Kondapur",
          areaName: "Madhapur",
          costForTwo: "50000",
          costForTwoMessage: "₹500 FOR TWO",
          cuisines: ["North Indian", "Chinese"],
          avgRating: 3.9,
          feeDetails: {},
          avgRatingString: "3.9",
          totalRatingsString: "5K+",
          sla: {
            deliveryTime: 60,
            minDeliveryTime: 55,
            maxDeliveryTime: 60,
            lastMileTravel: 13.7,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "55-60 MINS",
            lastMileTravelString: "13.6 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          aggregatedDiscountInfo: {
            visible: true,
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV2: {
            visible: true,
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.8",
              ratingCount: "500+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "89762",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "89762",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "168818",
          name: "Behrouz Biryani",
          city: "3",
          slugs: {
            restaurant: "behrouz-biryani-suchitra-jeedimetla-chintal",
            city: "hyderabad",
          },
          cloudinaryImageId: "htra1ceo32gospqkqalp",
          address:
            "First Floor, Block No 7, Krishna Nagar, Jeedimetla Village, Qutbullapur Mandal, Rangareddy District, Hyderabad 500055",
          locality: "Suchitra",
          areaName: "Quthbullapur",
          costForTwo: "50000",
          costForTwoMessage: "₹500 FOR TWO",
          cuisines: [
            "Biryani",
            "Kebabs",
            "Mughlai",
            "Lucknowi",
            "Hyderabadi",
            "Desserts",
            "Beverages",
          ],
          avgRating: 4,
          feeDetails: {},
          avgRatingString: "4.0",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 39,
            minDeliveryTime: 35,
            maxDeliveryTime: 40,
            lastMileTravel: 4.1,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "35-40 MINS",
            lastMileTravelString: "4.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {
            imageBadges: [
              {
                imageId: "newg.png",
                description: "Gourmet",
              },
            ],
          },
          aggregatedDiscountInfoV3: {
            header: "₹125 OFF",
            subHeader: "ABOVE ₹199",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "168818",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "168818",
            query: "Chicken Biryani",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "261393",
          name: "Midnight Biryani Hub",
          city: "3",
          slugs: {
            restaurant: "midnight-birya-hub-kukatpally-kukatpally",
            city: "hyderabad",
          },
          cloudinaryImageId: "fcf355b410242963d3751bf6762244d6",
          address:
            "H.NO 2-22-149/2, SHUBHODAYA COLONY,KUKATPALLY, HYDERABAD, Circle No.14(Kukatpally),Hyderabad- West Zone, Telangana",
          locality: "Kukatpally",
          areaName: "Kukatpally",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Beverages", "Chinese", "Hyderabadi", "Indian", "Mughlai"],
          avgRating: 2.9,
          feeDetails: {},
          avgRatingString: "2.9",
          totalRatingsString: "500+",
          sla: {
            deliveryTime: 62,
            minDeliveryTime: 60,
            maxDeliveryTime: 65,
            lastMileTravel: 3.8,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "60-65 MINS",
            lastMileTravelString: "3.7 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "60% OFF",
            subHeader: "UPTO ₹120",
          },
          ratingSlab: "RATING_SLAB_3",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "5.0",
              ratingCount: "1",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "261393",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            restaurant_id: "261393",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "189424",
          name: "The Biryani Life",
          city: "3",
          slugs: {
            restaurant: "the-biryani-life-suchitra-jeedimetla-chintal",
            city: "hyderabad",
          },
          cloudinaryImageId: "b6abc969a8641e511510359c9468476e",
          address:
            "First Floor, Block No 7, Krishna Nagar, Jeedimetla Village, Qutbullapur Mandal, Rangareddy District, Hyderabad 500055",
          locality: "Suchitra",
          areaName: "Quthbullapur",
          costForTwo: "25000",
          costForTwoMessage: "₹250 FOR TWO",
          cuisines: [
            "Biryani",
            "Mughlai",
            "Lucknowi",
            "Hyderabadi",
            "Kebabs",
            "Desserts",
            "Beverages",
          ],
          avgRating: 3.7,
          feeDetails: {},
          avgRatingString: "3.7",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 50,
            minDeliveryTime: 45,
            maxDeliveryTime: 50,
            lastMileTravel: 4.1,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "45-50 MINS",
            lastMileTravelString: "4.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          aggregatedDiscountInfoV3: {
            header: "50% OFF",
            subHeader: "UPTO ₹100",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "189424",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            restaurant_id: "189424",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "844742",
          name: "AZAM HOTEL",
          city: "3",
          slugs: {
            restaurant: "azam-hotel-secunderabad-secunderabad",
            city: "hyderabad",
          },
          cloudinaryImageId:
            "FOOD_CATALOG/IMAGES/CMS/2024/3/13/e0a6013e-4aa4-4b4f-ba75-8b6d56109d0a_e263b87c-26d7-4be8-bbfc-d861a83b6b26.jpeg",
          address:
            "SY NO 265, Beside Abubakar Masjid, Chinna Thokatta, New Bowenpally main road, Cantonment-Secunderabad, Telangana-500011",
          locality: "Secunderabad",
          areaName: "NEW BOWENPALLY",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Biryani", "Haleem", "shawarma", "Chinese", "Hyderabadi"],
          avgRating: 4.3,
          feeDetails: {},
          avgRatingString: "4.3",
          totalRatingsString: "500+",
          sla: {
            deliveryTime: 47,
            minDeliveryTime: 45,
            maxDeliveryTime: 50,
            lastMileTravel: 5.7,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_NONE",
            slaString: "45-50 MINS",
            lastMileTravelString: "5.6 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          aggregatedDiscountInfoV3: {
            header: "15% OFF",
            subHeader: "ABOVE ₹500",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_5",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "844742",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            restaurant_id: "844742",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "249730",
          name: "Biryaniwala",
          city: "3",
          slugs: {
            restaurant: "biryani-wala-madhapur-madhapur",
            city: "hyderabad",
          },
          cloudinaryImageId: "houbylbtgz9xayxlqexl",
          address: "PLOT NO 64,OPPOSITE RR KADAPA RUCHULU AYYAPASOCIETY.",
          locality: "AYYAPASOCIETY",
          areaName: "Chanda Naik Nagar",
          costForTwo: "20000",
          costForTwoMessage: "₹200 FOR TWO",
          cuisines: ["Biryani", "North Indian", "Snacks", "Chinese", "Mughlai"],
          avgRating: 3.5,
          feeDetails: {},
          avgRatingString: "3.5",
          totalRatingsString: "5K+",
          sla: {
            deliveryTime: 62,
            minDeliveryTime: 60,
            maxDeliveryTime: 65,
            lastMileTravel: 10.9,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "60-65 MINS",
            lastMileTravelString: "10.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "₹150 OFF",
            subHeader: "ABOVE ₹299",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "249730",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "249730",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "1110",
          name: "Hitech Bawarchi",
          city: "3",
          slugs: {
            restaurant: "hitech-bawarchi-ayyappa-society-madhapur",
            city: "hyderabad",
          },
          cloudinaryImageId: "0b6ebf47933db01fa997df2492b4f006",
          address: "Opp Indian Oil Petrol Bunk, Madhapur, Hyderabad",
          locality: "Madhapur",
          areaName: "Madhapur",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
          avgRating: 3.9,
          feeDetails: {},
          avgRatingString: "3.9",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 84,
            minDeliveryTime: 80,
            maxDeliveryTime: 85,
            lastMileTravel: 12.3,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "80-85 MINS",
            lastMileTravelString: "12.3 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseMessage: "Closes soon",
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {
            textExtendedBadges: [
              {
                iconId: "guiltfree/GF_Logo_android_3x",
                shortDescription: "options available",
                fontColor: "#7E808C",
              },
            ],
          },
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "₹125 OFF",
            subHeader: "ABOVE ₹299",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.6",
              ratingCount: "1K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "1110",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            restaurant_id: "1110",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "503987",
          name: "Baburao Gari Biryani",
          city: "3",
          slugs: {
            restaurant: "baburao-gari-biryani-kukatpally-kukatpally",
            city: "hyderabad",
          },
          cloudinaryImageId: "ee8c46bdb8025fa495ce2c1d2286d89d",
          address:
            "H.NO:- 2-22-98/B, VIJAYA NAGAR COLONY, KUKATPALLY, HYDERABAD, Kukatpally Circle No 24, Hyderabad",
          locality: "Kukatpally",
          areaName: "Kukatpally",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["Biryani", "Hyderabadi", "Andhra", "South Indian"],
          avgRating: 3.9,
          feeDetails: {},
          avgRatingString: "3.9",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 66,
            minDeliveryTime: 65,
            maxDeliveryTime: 70,
            lastMileTravel: 5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "65-70 MINS",
            lastMileTravelString: "5.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "10% OFF",
            subHeader: "ABOVE ₹850",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.7",
              ratingCount: "100+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "503987",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "503987",
            query: "Chicken Biryani",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "63087",
          name: "Biryanis And More",
          city: "3",
          slugs: {
            restaurant: "biryanis-and-more-ameerpet-ameerpet",
            city: "hyderabad",
          },
          cloudinaryImageId: "e8eairtd3nlnqooxdpjy",
          address:
            "8-3-214/3, Srinivasa Nagar W, Srinivasa Nagar West, Ameerpet, Hyderabad, Telangana 500038, India",
          locality: "Khairatabad",
          areaName: "Ameerpet",
          costForTwo: "30000",
          costForTwoMessage: "₹300 FOR TWO",
          cuisines: ["North Indian", "South Indian", "Chinese", "Tandoor"],
          avgRating: 4.1,
          feeDetails: {},
          avgRatingString: "4.1",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 69,
            minDeliveryTime: 65,
            maxDeliveryTime: 70,
            lastMileTravel: 7,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "65-70 MINS",
            lastMileTravelString: "7.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          aggregatedDiscountInfo: {
            visible: true,
          },
          badges: {},
          aggregatedDiscountInfoV2: {
            visible: true,
          },
          ratingSlab: "RATING_SLAB_5",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "63087",
          impressionObjectName: "impression-restaurant",
          clickObjectName: "click-restaurant",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
            source: "SEARCH",
            isSld: "false",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "63087",
            query: "Chicken Biryani",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "1128",
          name: "Paradise Biryani",
          city: "3",
          slugs: {
            restaurant: "paradise-opposite-cyber-tower-hitech-city-madhapur",
            city: "hyderabad",
          },
          cloudinaryImageId: "1e213b9b447d3bbedf54a57013f6c669",
          address:
            "Beside Shilpa Kalavedika, Opposite Cyber Tower, Hitech City",
          locality: "Hitech City",
          areaName: "Hitech City",
          costForTwo: "40000",
          costForTwoMessage: "₹400 FOR TWO",
          cuisines: [
            "Biryani",
            "Kebabs",
            "North Indian",
            "Hyderabadi",
            "Rolls & Wraps",
          ],
          avgRating: 4,
          feeDetails: {},
          avgRatingString: "4.0",
          totalRatingsString: "10K+",
          sla: {
            deliveryTime: 63,
            minDeliveryTime: 60,
            maxDeliveryTime: 65,
            lastMileTravel: 13.5,
            serviceability: "SERVICEABLE",
            rainMode: "RAIN_MODE_LIGHT",
            slaString: "60-65 MINS",
            lastMileTravelString: "13.5 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            opened: true,
            restaurantClosedMeta: {},
          },
          badges: {},
          sld: true,
          aggregatedDiscountInfoV3: {
            header: "₹150 OFF",
            subHeader: "ABOVE ₹599",
            discountTag: "FLAT DEAL",
          },
          ratingSlab: "RATING_SLAB_4",
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          cartOrderabilityNudgeBanner: {
            parameters: {},
            presentation: {},
          },
          externalRatings: {
            aggregatedRating: {
              rating: "3.8",
              ratingCount: "10K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
        },
        analytics: {
          screenName: "explore",
          context:
            '{"tid":"undefined","grid":"a4533af3-1c79-4592-83f1-fd0b71b777e0","queryUniqueId":"82a57b39-eb41-4c65-0b98-43a3559cdc68","query":"Chicken Biryani"}',
          objectValue: "1128",
          impressionObjectName: "impression-restaurant-sld",
          clickObjectName: "click-restaurant-sld",
        },
        ctaWithParams: {
          link: "swiggy://menu",
          type: "DEEPLINK",
          params: {
            source: "SEARCH",
            isSld: "true",
            sourceRequestId: "668442d76eacb359d0c82c4718af6aeb",
            restaurant_id: "1128",
            query: "Chicken Biryani",
            sourceSessionId: "eqn722c6-c73e-4990-a005-dd840bd6c94f",
          },
        },
      },
    },
  },
];
